#!/usr/bin/env php
<?php

if (php_sapi_name() !== "cli") exit;

require __DIR__ . "/vendor/autoload.php";

use Rudra\Cli\Console;
use App\Ship\ShipController;
use Symfony\Component\Yaml\Yaml;
use Rudra\Container\Facades\Rudra;
use Rudra\Cli\ConsoleFacade as Cli;

parse_str(implode('&', array_slice($argv, 1)), $inputArgs);

$env = getenv('APP_ENV');
if ($env === false || $env === '') {
    $envFile = __DIR__ . '/app_env.php';
    $env = file_exists($envFile) ? require $envFile : 'local';
}

Rudra::config(Yaml::parseFile($configFile));
Rudra::config()->set(["app.path" => realpath(__DIR__)]);
Rudra::config()->set(require_once "app/Ship/config.php");
Rudra::binding(Rudra::config()->get("contracts"));
Rudra::waiting(Rudra::config()->get("services"));
Rudra::set([Console::class, Console::class]);

(new ShipController())->eventRegistration();

foreach (Yaml::parseFile("config/commands.yml") as $name => $command) {
    Cli::addCommand($name, $command);
}

Cli::invoke($inputArgs);
