### RBAC ###
role:
    admin: ['C', 'U', 'D']
    editor: ['C', 'U']
    moderator: ['U']

### Соль - для кеширования пароля ###
salt: '123'

#re.сaptcha:
#    site.key: # Ключ reCaptcha для фронтенда
#    secret: # Ключ reCaptcha для бекэнда

# Параметр использующийся для маршрутизации
# REQUEST - $_SERVER['REQUEST_URI'] с правилом в .htaccess
# RewriteRule ^(.*)$ index.php [L,QSA]
# GET - $_GET['r'], в .htaccess необходимо указать правило
# RewriteRule ^(.*)$ index.php?r=$1 [L,QSA]
uri: request

### Base path ###
### path to yours home folder/ ###
bp: /home/d/projects/rudra/Rudra-Framework/

### Environment ###
env: development

# Шаблонизатор
# twig или php
template:
    web:
        engine: twig
        view.path: app/web/Resources/twig/view
        cache.path: app/web/Resources/twig/compilation_cache

# Базовое пространство имен
namespaces:
    web: App\Web\

# БД
database:
    active: pdo
    pdo:
        driver: PDO
        DSN: mysql
        host: localhost
        user: root
        password: ''
        name: rudra
    eloquent:
        driver: Eloquent
        DSN: mysql
        host: localhost
        user: root
        password: ''
        name: rudra
    doctrine:
        driver: Doctrine
        DSN: pdo_mysql
        host: localhost
        user: root
        password: ''
        name: rudra

http.errors:
    404:
        controller: App\Web\WebController
        method: error404
    503:
        controller: App\Web\WebController
        method: error503
