secret: '1234567891011121' # Need to be changed
environment: production
cache.time:
    routes: now
    templates: now
    database: now
roles:
    admin: 0
    editor: 1
    moderator: 2
    user: 3
http.errors:
    404:
        controller: App\Ship\Errors\Controller\HttpErrorsController 
        action: error404
    503: 
        controller: App\Ship\Errors\Controller\HttpErrorsController
        action: error503
database:
    dsn: mysql:dbname=rudra_mysql;host=127.0.0.1
    # dsn: pgsql:host=127.0.0.1;port=5432;dbname=rudra_postgres;
    # dsn: sqlite:/home/d/Public/Рудра фреймворк/Rudra-Framework/app/Ship/Data/rudra.sqlite
    username: jagepard
    password: password
attributes: true
containers:
    demo: App\Containers\Demo\