<?php
    use Rudra\Container\Facades\Rudra;
?>
<!doctype html>
<html lang="en">
  <head>
  <meta charset="UTF-8">
    <meta name="description" content="<?= $title ?>"/>
    <meta name="keywords" content="<?= $title ?>" />
    <meta name="author" content="Jagepard, jagepard@yandex.ru"/>
    <meta name="copyright" content="Jagepard">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?= $title ?></title>

    <link href="<?= Rudra::config()->get('url') ?>/assets/bootswatch/<?= $thema ?>.min.css" rel="stylesheet"/>
    <link href="<?= Rudra::config()->get('url') ?>/assets/css/prism.css" rel="stylesheet" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <?php if (Rudra::config()->get('environment') === 'development') {
        echo $debugbar->renderHead();
    } ?>
  </head>
  <body>
    
    <?= $content ?> 


    <?php if (Rudra::config()->get('environment') === 'development') {
        echo $debugbar->render();
    } ?>
    <script src="<?= Rudra::config()->get('url') ?>/assets/js/prism.js"></script>
  </body>
</html>