<?php
    use Rudra\Container\Facades\Rudra;
?>
<!doctype html>
<html lang="en">
  <head>
  <meta charset="UTF-8">
    <meta name="description" content="<?= $title ?>"/>
    <meta name="keywords" content="<?= $title ?>" />
    <meta name="author" content="Jagepard, jagepard@yandex.ru"/>
    <meta name="copyright" content="Jagepard">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?= $title ?></title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href="<?= Rudra::config()->get('url') ?>/css/prism.css" rel="stylesheet" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <?php if (Rudra::config()->get('environment') === 'development') {
        echo $debugbar->renderHead();
    } ?>
  </head>
  <body>
  <main>
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
          <img src="<?= Rudra::config()->get('url') ?>/images/rudra.png" alt="Rudra Framework" width="5%">
        <span class="fs-4">Rudra Framework</span>
      </a>
    </header>
    
    <?= $content ?> 

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; <a href="https://github.com/Jagepard">Jagepard</a> <?= date('Y') ?>
    </footer>
  </div>
</main>

    <?php if (Rudra::config()->get('environment') === 'development') {
        echo $debugbar->render();
    } ?>
    <script src="<?= Rudra::config()->get('url') ?>/js/prism.js"></script>
  </body>
</html>